# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AfTui < Formula
  desc "AgentFactory TUI — terminal dashboard for AI agent fleets"
  homepage "https://github.com/RenseiAI/agentfactory-tui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v0.1.0/agentfactory-tui_0.1.0_darwin_amd64.tar.gz"
      sha256 "291d842d10511c03ab29c9e6d5217a19f484986bba865c472a2da4d4fb66715f"

      define_method(:install) do
        bin.install "af-tui"
        bin.install "af-status"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v0.1.0/agentfactory-tui_0.1.0_darwin_arm64.tar.gz"
      sha256 "d8eb9ddee03841b5ac0fa80a08a413595e0eee189ffbdddcf89ec41725c9f984"

      define_method(:install) do
        bin.install "af-tui"
        bin.install "af-status"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v0.1.0/agentfactory-tui_0.1.0_linux_amd64.tar.gz"
      sha256 "91d696c24190a324785455a6ee2abdfde6edaa0c19819ccab690af8d02c89deb"
      define_method(:install) do
        bin.install "af-tui"
        bin.install "af-status"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v0.1.0/agentfactory-tui_0.1.0_linux_arm64.tar.gz"
      sha256 "57d2d8dde64409cbe9a0c2637c15510bda8fa9b8125d3bd3846fa4342ba90215"
      define_method(:install) do
        bin.install "af-tui"
        bin.install "af-status"
      end
    end
  end
end
