# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AfTui < Formula
  desc "AgentFactory TUI — terminal dashboard for AI agent fleets"
  homepage "https://github.com/RenseiAI/agentfactory-tui"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v0.1.1/agentfactory-tui_0.1.1_darwin_amd64.tar.gz"
      sha256 "0eaca438562e98d009ff5cc94ac81c8a5519be98b5b7a64cd18f04d03c234113"

      define_method(:install) do
        bin.install "af-tui"
        bin.install "af-status"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v0.1.1/agentfactory-tui_0.1.1_darwin_arm64.tar.gz"
      sha256 "5714b5a662a0494c7346bb6c3f5fcb70dff3150a8fedf020d9b5a16c488578fe"

      define_method(:install) do
        bin.install "af-tui"
        bin.install "af-status"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v0.1.1/agentfactory-tui_0.1.1_linux_amd64.tar.gz"
      sha256 "603bc5c47e6c5f83e1f6458d420a1e4b7c4ffb8fdc72aa19f2cfd82f3c76da8e"
      define_method(:install) do
        bin.install "af-tui"
        bin.install "af-status"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v0.1.1/agentfactory-tui_0.1.1_linux_arm64.tar.gz"
      sha256 "f497ad472db790509dc00b836fcbf9ab382fff6d90a2af2735d862f7f679aafd"
      define_method(:install) do
        bin.install "af-tui"
        bin.install "af-status"
      end
    end
  end
end
