# This file was generated by GoReleaser. DO NOT EDIT.
cask "af-tui" do
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/agentfactory-tui_#{version}_darwin_amd64.tar.gz"
      sha256 "baaca49188891601b49e46e1680909d4e3a3b8abd0f53d738e2039c0934ea6cd"
    end
    on_arm do
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/agentfactory-tui_#{version}_darwin_arm64.tar.gz"
      sha256 "8115ebd4b06280634f1cb7865164e8adc9559c0e5c5f2d4350271fca45e175e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/agentfactory-tui_#{version}_linux_amd64.tar.gz"
      sha256 "5ff82329303d97180924d1e8d444f45a2cb82f31fde5719b7153e90962ed63a8"
    end
    on_arm do
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/agentfactory-tui_#{version}_linux_arm64.tar.gz"
      sha256 "5ce83d3d528f1d359447a07136ed72327ddcd26027e40eb439845d9a839987d5"
    end
  end

  name "af-tui"
  desc "AgentFactory TUI — terminal dashboard for AI agent fleets"
  homepage "https://github.com/RenseiAI/agentfactory-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "af-tui"
  binary "af-status"

  # No zap stanza required

end
