# This file was generated by GoReleaser. DO NOT EDIT.
cask "af" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "5cd63971941f0d86693d7902348f56b385b2e66251a883de456560b6775e84e6"
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/af_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "89d012fb4317816e013693c7b4f822fea2419543ff952e395c14062041ad9d0b"
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/af_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fc834438830a6e4e48368dcbcef6da0e5af3aa02c07b090711134dd02e27bff4"
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/af_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "df0d8cea05aa8a0ea9a44e33eb3c6e3d444a5e6263154dc11e13502c29d1a2e7"
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/af_#{version}_linux_arm64.tar.gz"
    end
  end

  name "af"
  desc "AgentFactory CLI — terminal dashboard and CLI for AI agent fleets"
  homepage "https://github.com/RenseiAI/agentfactory-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "af"

  # No zap stanza required

end
