# This file was generated by GoReleaser. DO NOT EDIT.
cask "af" do
  version "0.7.2"

  on_macos do
    on_intel do
      sha256 "9bb500d37a740fd4112cf2b402650bd28ac48b063b751d924c98a578a52dbb39"
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/af_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2578963eb9c497f37ad7853f76a14c9fac4b577803e71b88df42f96529bf0c11"
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/af_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "55b9f2a676b27c7fc28e86341bf9490ad4fa3f4528d5deae0b8c85ec852a20d6"
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/af_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "32c3fd6789b54bd63ef8b090df376169e3ce7aa2d3a64e162ae465d5e7535ef2"
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/af_#{version}_linux_arm64.tar.gz"
    end
  end

  name "af"
  desc "AgentFactory CLI — terminal dashboard and CLI for AI agent fleets"
  homepage "https://github.com/RenseiAI/agentfactory-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "af"

  # No zap stanza required

end
