# This file was generated by GoReleaser. DO NOT EDIT.
cask "af" do
  version "0.7.7"

  on_macos do
    on_intel do
      sha256 "cd837661287127f5b3f5a075cbd62fd1b6ba1e9a1df7e0b42a69cbe250b2d17e"
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/af_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f70e6bf63f982b7dd2da2509aecd17da8066035b638af7dd8aa082cccc08a9dd"
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/af_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "26a7f0359d7daef15d987e9586d2aa97285717a8b10dea03f0b9cff6a102dd4d"
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/af_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "49b9e1d4697b5ddf49147dc2bb9351c9627feb634d29e6ce725c9c94ac173483"
      url "https://github.com/RenseiAI/agentfactory-tui/releases/download/v#{version}/af_#{version}_linux_arm64.tar.gz"
    end
  end

  name "af"
  desc "AgentFactory CLI — terminal dashboard and CLI for AI agent fleets"
  homepage "https://github.com/RenseiAI/agentfactory-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "af"

  # No zap stanza required

end
