# This file was generated by GoReleaser. DO NOT EDIT.
cask "donmai" do
  version "0.68.8"

  on_macos do
    on_intel do
      sha256 "4080a0a6c4560d7bd0add602685b8f1bf740016369c2a766d8a11615091a5efa"
      url "https://github.com/RenseiAI/donmai/releases/download/v#{version}/donmai_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "34c13d150016437927471a01818be8ac5ee887cb4406efb42a96d1f1d461accc"
      url "https://github.com/RenseiAI/donmai/releases/download/v#{version}/donmai_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4a256be3f9d7e7d8746350f262598c1647e7f20e232ed21987cf688ef4fc248f"
      url "https://github.com/RenseiAI/donmai/releases/download/v#{version}/donmai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7d8ffcfdbb22531fbc048d3a4cabce92f3cc7039956f184bc405848232a8329c"
      url "https://github.com/RenseiAI/donmai/releases/download/v#{version}/donmai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "donmai"
  desc "Donmai CLI — terminal dashboard and CLI for AI agent fleets"
  homepage "https://github.com/RenseiAI/donmai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "donmai"

  # No zap stanza required

end
