# This file was generated by GoReleaser. DO NOT EDIT.
cask "donmai" do
  version "0.72.5"

  on_macos do
    on_intel do
      sha256 "16f421090d471c6785b8871d9ee944cac75f89b5b2df76e38b3a0e6c17cb99ea"
      url "https://github.com/RenseiAI/donmai/releases/download/v#{version}/donmai_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f5b523955beebe879a97b0614318a2fd691abc3f2efc646ab37255eddf109409"
      url "https://github.com/RenseiAI/donmai/releases/download/v#{version}/donmai_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "37d0bf97f54548658a39416c5c52998e75a3c05ecde3eaadb0dce59d61cb3029"
      url "https://github.com/RenseiAI/donmai/releases/download/v#{version}/donmai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cdd53a69626da5b1b8bcf462461db7242aa5104144a04497dc84f2b87f36314f"
      url "https://github.com/RenseiAI/donmai/releases/download/v#{version}/donmai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "donmai"
  desc "Donmai CLI — terminal dashboard and CLI for AI agent fleets"
  homepage "https://github.com/RenseiAI/donmai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "donmai"

  # No zap stanza required

end
