# This file was generated by GoReleaser. DO NOT EDIT.
cask "donmai" do
  version "0.49.2"

  on_macos do
    on_intel do
      sha256 "fcea39a5c09be52f1a75524dbea43a9ef0b8ac15a623f197c16ccf71480bd90c"
      url "https://github.com/RenseiAI/donmai/releases/download/v#{version}/donmai_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fbe7497aafe8a2f8116448b5f63636107430e1344efb134e6b96224b6919a07e"
      url "https://github.com/RenseiAI/donmai/releases/download/v#{version}/donmai_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7d0fdefcb6f7c47ac4aebce50025cfb00eb532fc222842af60085c06b93f0e52"
      url "https://github.com/RenseiAI/donmai/releases/download/v#{version}/donmai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef3e8af2a78196b1d9405b914160a2601bb54a4e671e9469eca6bfc4d9cd9709"
      url "https://github.com/RenseiAI/donmai/releases/download/v#{version}/donmai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "donmai"
  desc "Donmai CLI — terminal dashboard and CLI for AI agent fleets"
  homepage "https://github.com/RenseiAI/donmai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "donmai"

  # No zap stanza required

end
