# This file was generated by GoReleaser. DO NOT EDIT.
cask "rensei" do
  version "0.11.40"

  on_macos do
    on_intel do
      sha256 "8bd790570cae04d011d91c1c9d13a8745a9c95e6719b852c7efce6317dd5be74"
      url "https://github.com/RenseiAI/releases/releases/download/v#{version}/rensei_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/RenseiAI/releases/"
    end
    on_arm do
      sha256 "33df97a39dc4c4993564035a756f8937d3cf65f2486020748e153f6fb57719e5"
      url "https://github.com/RenseiAI/releases/releases/download/v#{version}/rensei_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/RenseiAI/releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "a9c578befe5013640b84f354a1d13baa20018179d9acba1c847e4ae063603659"
      url "https://github.com/RenseiAI/releases/releases/download/v#{version}/rensei_#{version}_linux_amd64.tar.gz",
        verified: "github.com/RenseiAI/releases/"
    end
    on_arm do
      sha256 "16e7590ae03c19f22cd9f4195035d61aa0c61cffd98f36215abd8cf72381fbea"
      url "https://github.com/RenseiAI/releases/releases/download/v#{version}/rensei_#{version}_linux_arm64.tar.gz",
        verified: "github.com/RenseiAI/releases/"
    end
  end

  name "rensei"
  desc "Rensei — AI Agent Platform CLI"
  homepage "https://rensei.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rensei"

  # No zap stanza required

end
