# This file was generated by GoReleaser. DO NOT EDIT.
cask "rensei" do
  version "0.8.3"

  on_macos do
    on_intel do
      sha256 "2a154eb13690e28a4907ae4ab08825b0776f903ff31b2a6bac89399a40a92760"
      url "https://github.com/RenseiAI/releases/releases/download/v#{version}/rensei_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/RenseiAI/releases/"
    end
    on_arm do
      sha256 "52f04b269fdff13d7d1a3ef82995e19fc3858c04d3627bfb895f5599fd9991b4"
      url "https://github.com/RenseiAI/releases/releases/download/v#{version}/rensei_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/RenseiAI/releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "be43285816cfa8df699a819b5527c76f5a2c8e4cb015c72e317375f2256de309"
      url "https://github.com/RenseiAI/releases/releases/download/v#{version}/rensei_#{version}_linux_amd64.tar.gz",
        verified: "github.com/RenseiAI/releases/"
    end
    on_arm do
      sha256 "246bae81e0a34ce5bbd14d8070eab04c4b5ed23245020beeb923219c110f14fc"
      url "https://github.com/RenseiAI/releases/releases/download/v#{version}/rensei_#{version}_linux_arm64.tar.gz",
        verified: "github.com/RenseiAI/releases/"
    end
  end

  name "rensei"
  desc "Rensei — AI Agent Platform CLI"
  homepage "https://rensei.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rensei"

  # No zap stanza required

end
