# This file was generated by GoReleaser. DO NOT EDIT.
cask "rensei" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "b16da0c4e54c3460ff7b12f10331162873fe60cdc46f7b4fccf5447708405ae3"
      url "https://github.com/RenseiAI/releases/releases/download/v#{version}/rensei_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/RenseiAI/releases/"
    end
    on_arm do
      sha256 "4b1aee05cf041ce081c0fc6c48c21b1f74450caaa95c0fab2845bb741bb5fe5e"
      url "https://github.com/RenseiAI/releases/releases/download/v#{version}/rensei_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/RenseiAI/releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "9e343af4e678878369b2622d98f304a561ea19b8802722f157db4a6eaf26d805"
      url "https://github.com/RenseiAI/releases/releases/download/v#{version}/rensei_#{version}_linux_amd64.tar.gz",
        verified: "github.com/RenseiAI/releases/"
    end
    on_arm do
      sha256 "e8350b71307c4a5de2d41762594270ad7bde1d85d709dee60af3c6009b3a3280"
      url "https://github.com/RenseiAI/releases/releases/download/v#{version}/rensei_#{version}_linux_arm64.tar.gz",
        verified: "github.com/RenseiAI/releases/"
    end
  end

  name "rensei"
  desc "Rensei — AI Agent Platform CLI"
  homepage "https://rensei.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rensei"

  # No zap stanza required

end
